### ISSUE TITLE
Can't make it work on Docker Desktop K8s (Mac)

### ISSUE THREAD

**Issue by ecorro** [https-deeplearning-ai/machine-learning-engineering-for-production-public#54]
Hi

In order to make the deployment work on K8s by Docker Desktop (Mac) I had to modify the deployment manifest:

  ```
    volumes:
        - name: tf-serving-volume
          hostPath:
            #path: /var/tmp/saved_model_half_plus_two_cpu
            path: /tmp/saved_model_half_plus_two_cpu
            #type: Directory
```

Then verified the deployment was up and running:

```
kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
tf-serving-deployment-6c4f4dc9d6-nbhq8   1/1     Running   0          53m
```

Then I forwarded the pod port:

```
kubectl port-forward tf-serving-deployment-6c4f4dc9d6-nbhq8 8501:8501
Forwarding from 127.0.0.1:8501 -> 8501
Forwarding from [::1]:8501 -> 8501

```

And when trying to run a POST command to get a prediction, the pod refuses the connection request:

```
curl -d '{"instances": [1.0, 2.0, 5.0]}' -X POST http://localhost:8501/v1/models/half_plus_two:predict
curl: (52) Empty reply from server

```

`E0225 10:46:00.303384   62138 portforward.go:400] an error occurred forwarding 8501 -> 8501: error forwarding port 8501 to pod aaecd472db77fbd0d7684f213bf653f70f4fdede346e05d5c2b255d3b495fed4, uid : exit status 1: 2022/02/25 16:46:00 socat[36952] E connect(16, AF=2 127.0.0.1:8501, 16): Connection refused`

This is unusual to me as K8s from Docker Desktop normally behave like a regular K8s deployment. I'd appreciate some guidance as I think that it'd be good to understand how TF serving works in a real K8s cluster and not only on Minikube/VirtualBox.

thanks
